project:
  type: book

book:
  title: "Antibiotic Therapy: Discovery, Development, and Rationale Clinical Use"
  author: "Russell E. Lewis"
  date: "6/7/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - origin.qmd
    - summary.qmd
    - references.qmd
bibliography: references.bib
csl: nature.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

